### ISSUE TITLE
Log settings for Nginx is not working

### ISSUE THREAD

**Issue by dmytro** [dmytro/capistrano-recipes#15]
On reload Nginx generates following errors:

```
* Reloading nginx configuration nginx
   nginx: [warn] the "log_format" directive may be used only on "http" level in /etc/nginx/sites-enabled/coiney-rails:30
```

Seems it is because of this commit:

https://github.com/dmytro/capistrano-recipes/commit/c9c73aefcf9fe04619611bbfb11dcc17c44b32c7

@zentaHori Could you please take a look?

**Comment by zentahori** [comment]
This is already fixed.
Close this issue.
